### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by henry2004y** [halleysfifthinc/Peaks.jl#15]
I am a little bit surprised about the performance of `argmaxima` compared with a direct implementation:
```julia
using Test, BenchmarkTools
using Peaks

function localmaxmin!(y, maxs::Vector{Int}, mins::Vector{Int})
   empty!(maxs)
   empty!(mins)
   for i in 2:length(y)-1
       if y[i+1] < y[i] > y[i-1]
           push!(maxs, i)
       elseif y[i+1] > y[i] < y[i-1]
           push!(mins, i)
       end
   end
end

function localmaxmin2!(x, maxs, mins)
   append!(maxs2, argmaxima(x))
   append!(mins2, argminima(x))
   maxs2, mins2
end

function localmax(y)
   maxs = Int[]
   for i in 2:length(y)-1
       if y[i+1] < y[i] > y[i-1]
           push!(maxs, i)
       end
   end
   maxs
end

function localmax2(x)
   maxs2 = argmaxima(x)
end

maxs = Int[]
mins  = Int[]
maxs2= Int[]
mins2 = Int[]
x = zeros(100000)
x_max = 2:100:100000
x[x_max] .= 1
x_min = 5:100:100000
x[x_min] .= -1
localmaxmin!(x, maxs, mins)
localmaxmin2!(x, maxs2, mins2)

@test maxs == maxs2
@test mins == mins2

@btime localmax(x)
@btime localmax2(x)
@test localmax(x) == localmax2(x)
```
On my laptop, this returns
```julia
102.428 μs (10 allocations: 16.39 KiB)
380.387 μs (6 allocations: 398.92 KiB)
Test Passed
```
which is 3 times slower.

**Comment by halleysfifthinc** [comment]
Actually its almost 4x slower! I too am surprised by the size of the difference in performance! I'm also surprised about the difference in allocation size.

The `argmaxima` function has more features which explains at least some of the decreased performance compared to your `localmax` function: `argmaxima` supports larger/custom window sizes, identification of plateaus, and handles the presence of `NaN`s and `missing`s. The latter two features likely contribute the bulk of the increased runtime.

In any case, if the `localmax` function meets your needs, it doesn't appear to that switching to `Peaks.jl` would be beneficial, at the moment.

**Comment by a-11-hacker** [comment]
can you teach me to create a software for cnc machine
