### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by IgnacioRubioScola** [halleysfifthinc/Peaks.jl#17]
HI,
Do you have some bibliography explaining the implemented code?
I would like to understand how the algorithm of finding peaks (and the prominences) works
Thank you!
Ignacio

**Comment by halleysfifthinc** [comment]
The peak finding algorithm is wholly original, but the prominence algorithm was modeled after the MATLAB documentation description of the relevant algorithms. (I.e. not based on the actual MATLAB code, but their documented description of the behavior.) I don't recall whether the behavior for peak plateaus was based on MATLAB and/or scipy. Behavior for missing/NaNs and `strict` is mostly original as well.

Also see [Topographic prominence](https://en.wikipedia.org/wiki/Topographic_prominence)
