### ISSUE TITLE
Functions are not importing

### ISSUE THREAD

**Issue by usmcamp0811** [halleysfifthinc/Peaks.jl#2]
On Julia v1.0 I installed the package `Pkg.add("Peaks")` and then `using Peaks` and none of the functions are usable. My interpreter doesn't recognize the commands.

**Comment by halleysfifthinc** [comment]
Can you give me some more information? What is the output of `versioninfo()` and `] st`? There are only two functions on the current stable release of v0.0.1: `maxima` and `minima`. Can you try both of those and show the error?
