### ISSUE TITLE
Add peak separation

### ISSUE THREAD

**Issue by KronosTheLate** [halleysfifthinc/Peaks.jl#25]
It would be very nice to get an option to get a minimal peak separation, such as that found in https://github.com/tungli/Findpeaks.jl.

**Comment by halleysfifthinc** [comment]
Can you expand on what you mean by minimal peak separation (ideally with an example)? Does the window size argument `w` not do what you need?

**Comment by KronosTheLate** [comment]
No, you are absolutely right. As for the `peakheights` issue I mainly looked at the readme to see how to use the package. I also expected a separate function, as the other filtering functions seem to be separate functions. This is closed, and discussion on the discoverability can be continued at https://github.com/halleysfifthinc/Peaks.jl/issues/28.
