### ISSUE TITLE
Add number of peaks to look for

### ISSUE THREAD

**Issue by KronosTheLate** [halleysfifthinc/Peaks.jl#26]
It is currently not hard to do manually, but it would be very convenient to have a keyword argument to some function `see #24` that set the maximal and/or minimal number of peaks to look for, defaulting to `0` and `Inf`. I am using this in the context of calibrating a spectrogram, where I know the number of peaks I am looking for in advance, and in reality I just want the 4 most prominent peaks.

**Comment by halleysfifthinc** [comment]
Can you give an example or put together a PR for this? I'm not sure which of the functions you're thinking this would be for, and what/how exactly you're thinking this would work in terms of desired behavior.

**Comment by KronosTheLate** [comment]
Perhaps no internals need to be made. A `sortpekas` function, and just slicing peaks sorted by prominence, eould achieve what I want. I will look into it related to the API changes proposed

**Comment by KronosTheLate** [comment]
I will close this, and add a note in the API issue regarding `sortpeaks`.
