### ISSUE TITLE
Unusual behavior of peakprom?

### ISSUE THREAD

**Issue by ymtoo** [halleysfifthinc/Peaks.jl#4]
Maxima of an array of all zeros is
```julia
julia> peakprom(zeros(10), Maxima())
([2, 4, 6, 8], [0.0, 0.0, 0.0, 0.0])
```
instead of `(Int64[], Float64[])`.

**Comment by halleysfifthinc** [comment]
Good catch! I've got a PR in progress, and I should release a new version in a couple days.

**Comment by ymtoo** [comment]
Thanks!
